Championship.create!([
  {name: "F1 World Championship", year: 2018, points: "25 18 15 12 10 8 6 4 2 1"}
])
Country.create!([
  {name: "Afghanistan", shortname: "AF"},
  {name: "Albania", shortname: "AL"},
  {name: "Algeria", shortname: "DZ"},
  {name: "American Samoa", shortname: "DS"},
  {name: "Andorra", shortname: "AD"},
  {name: "Angola", shortname: "AO"},
  {name: "Anguilla", shortname: "AI"},
  {name: "Antarctica", shortname: "AQ"},
  {name: "Antigua and Barbuda", shortname: "AG"},
  {name: "Argentina", shortname: "AR"},
  {name: "Armenia", shortname: "AM"},
  {name: "Aruba", shortname: "AW"},
  {name: "Australia", shortname: "AU"},
  {name: "Austria", shortname: "AT"},
  {name: "Azerbaijan", shortname: "AZ"},
  {name: "Bahamas", shortname: "BS"},
  {name: "Bahrain", shortname: "BH"},
  {name: "Bangladesh", shortname: "BD"},
  {name: "Barbados", shortname: "BB"},
  {name: "Belarus", shortname: "BY"},
  {name: "Belgium", shortname: "BE"},
  {name: "Belize", shortname: "BZ"},
  {name: "Benin", shortname: "BJ"},
  {name: "Bermuda", shortname: "BM"},
  {name: "Bhutan", shortname: "BT"},
  {name: "Bolivia", shortname: "BO"},
  {name: "Bosnia and Herzegovina", shortname: "BA"},
  {name: "Botswana", shortname: "BW"},
  {name: "Bouvet Island", shortname: "BV"},
  {name: "Brazil", shortname: "BR"},
  {name: "British Indian Ocean Territory", shortname: "IO"},
  {name: "Brunei Darussalam", shortname: "BN"},
  {name: "Bulgaria", shortname: "BG"},
  {name: "Burkina Faso", shortname: "BF"},
  {name: "Burundi", shortname: "BI"},
  {name: "Cambodia", shortname: "KH"},
  {name: "Cameroon", shortname: "CM"},
  {name: "Canada", shortname: "CA"},
  {name: "Cape Verde", shortname: "CV"},
  {name: "Cayman Islands", shortname: "KY"},
  {name: "Central African Republic", shortname: "CF"},
  {name: "Chad", shortname: "TD"},
  {name: "Chile", shortname: "CL"},
  {name: "China", shortname: "CN"},
  {name: "Christmas Island", shortname: "CX"},
  {name: "Cocos (Keeling) Islands", shortname: "CC"},
  {name: "Colombia", shortname: "CO"},
  {name: "Comoros", shortname: "KM"},
  {name: "Congo", shortname: "CG"},
  {name: "Cook Islands", shortname: "CK"},
  {name: "Costa Rica", shortname: "CR"},
  {name: "Croatia (Hrvatska)", shortname: "HR"},
  {name: "Cuba", shortname: "CU"},
  {name: "Cyprus", shortname: "CY"},
  {name: "Czech Republic", shortname: "CZ"},
  {name: "Denmark", shortname: "DK"},
  {name: "Djibouti", shortname: "DJ"},
  {name: "Dominica", shortname: "DM"},
  {name: "Dominican Republic", shortname: "DO"},
  {name: "East Timor", shortname: "TP"},
  {name: "Ecuador", shortname: "EC"},
  {name: "Egypt", shortname: "EG"},
  {name: "El Salvador", shortname: "SV"},
  {name: "Equatorial Guinea", shortname: "GQ"},
  {name: "Eritrea", shortname: "ER"},
  {name: "Estonia", shortname: "EE"},
  {name: "Ethiopia", shortname: "ET"},
  {name: "Falkland Islands (Malvinas)", shortname: "FK"},
  {name: "Faroe Islands", shortname: "FO"},
  {name: "Fiji", shortname: "FJ"},
  {name: "Finland", shortname: "FI"},
  {name: "France", shortname: "FR"},
  {name: "France, Metropolitan", shortname: "FX"},
  {name: "French Guiana", shortname: "GF"},
  {name: "French Polynesia", shortname: "PF"},
  {name: "French Southern Territories", shortname: "TF"},
  {name: "Gabon", shortname: "GA"},
  {name: "Gambia", shortname: "GM"},
  {name: "Georgia", shortname: "GE"},
  {name: "Germany", shortname: "DE"},
  {name: "Ghana", shortname: "GH"},
  {name: "Gibraltar", shortname: "GI"},
  {name: "Guernsey", shortname: "GK"},
  {name: "Greece", shortname: "GR"},
  {name: "Greenland", shortname: "GL"},
  {name: "Grenada", shortname: "GD"},
  {name: "Guadeloupe", shortname: "GP"},
  {name: "Guam", shortname: "GU"},
  {name: "Guatemala", shortname: "GT"},
  {name: "Guinea", shortname: "GN"},
  {name: "Guinea-Bissau", shortname: "GW"},
  {name: "Guyana", shortname: "GY"},
  {name: "Haiti", shortname: "HT"},
  {name: "Heard and Mc Donald Islands", shortname: "HM"},
  {name: "Honduras", shortname: "HN"},
  {name: "Hong Kong", shortname: "HK"},
  {name: "Hungary", shortname: "HU"},
  {name: "Iceland", shortname: "IS"},
  {name: "India", shortname: "IN"},
  {name: "Isle of Man", shortname: "IM"},
  {name: "Indonesia", shortname: "ID"},
  {name: "Iran (Islamic Republic of)", shortname: "IR"},
  {name: "Iraq", shortname: "IQ"},
  {name: "Ireland", shortname: "IE"},
  {name: "Israel", shortname: "IL"},
  {name: "Italy", shortname: "IT"},
  {name: "Ivory Coast", shortname: "CI"},
  {name: "Jersey", shortname: "JE"},
  {name: "Jamaica", shortname: "JM"},
  {name: "Japan", shortname: "JP"},
  {name: "Jordan", shortname: "JO"},
  {name: "Kazakhstan", shortname: "KZ"},
  {name: "Kenya", shortname: "KE"},
  {name: "Kiribati", shortname: "KI"},
  {name: "Korea, Democratic Peoples Republic of", shortname: "KP"},
  {name: "Korea, Republic of", shortname: "KR"},
  {name: "Kosovo", shortname: "XK"},
  {name: "Kuwait", shortname: "KW"},
  {name: "Kyrgyzstan", shortname: "KG"},
  {name: "Lao Peoples Democratic Republic", shortname: "LA"},
  {name: "Latvia", shortname: "LV"},
  {name: "Lebanon", shortname: "LB"},
  {name: "Lesotho", shortname: "LS"},
  {name: "Liberia", shortname: "LR"},
  {name: "Libyan Arab Jamahiriya", shortname: "LY"},
  {name: "Liechtenstein", shortname: "LI"},
  {name: "Lithuania", shortname: "LT"},
  {name: "Luxembourg", shortname: "LU"},
  {name: "Macau", shortname: "MO"},
  {name: "Macedonia", shortname: "MK"},
  {name: "Madagascar", shortname: "MG"},
  {name: "Malawi", shortname: "MW"},
  {name: "Malaysia", shortname: "MY"},
  {name: "Maldives", shortname: "MV"},
  {name: "Mali", shortname: "ML"},
  {name: "Malta", shortname: "MT"},
  {name: "Marshall Islands", shortname: "MH"},
  {name: "Martinique", shortname: "MQ"},
  {name: "Mauritania", shortname: "MR"},
  {name: "Mauritius", shortname: "MU"},
  {name: "Mayotte", shortname: "TY"},
  {name: "Mexico", shortname: "MX"},
  {name: "Micronesia, Federated States of", shortname: "FM"},
  {name: "Moldova, Republic of", shortname: "MD"},
  {name: "Monaco", shortname: "MC"},
  {name: "Mongolia", shortname: "MN"},
  {name: "Montenegro", shortname: "ME"},
  {name: "Montserrat", shortname: "MS"},
  {name: "Morocco", shortname: "MA"},
  {name: "Mozambique", shortname: "MZ"},
  {name: "Myanmar", shortname: "MM"},
  {name: "Namibia", shortname: "NA"},
  {name: "Nauru", shortname: "NR"},
  {name: "Nepal", shortname: "NP"},
  {name: "Netherlands", shortname: "NL"},
  {name: "Netherlands Antilles", shortname: "AN"},
  {name: "New Caledonia", shortname: "NC"},
  {name: "New Zealand", shortname: "NZ"},
  {name: "Nicaragua", shortname: "NI"},
  {name: "Niger", shortname: "NE"},
  {name: "Nigeria", shortname: "NG"},
  {name: "Niue", shortname: "NU"},
  {name: "Norfolk Island", shortname: "NF"},
  {name: "Northern Mariana Islands", shortname: "MP"},
  {name: "Norway", shortname: "NO"},
  {name: "Oman", shortname: "OM"},
  {name: "Pakistan", shortname: "PK"},
  {name: "Palau", shortname: "PW"},
  {name: "Palestine", shortname: "PS"},
  {name: "Panama", shortname: "PA"},
  {name: "Papua New Guinea", shortname: "PG"},
  {name: "Paraguay", shortname: "PY"},
  {name: "Peru", shortname: "PE"},
  {name: "Philippines", shortname: "PH"},
  {name: "Pitcairn", shortname: "PN"},
  {name: "Poland", shortname: "PL"},
  {name: "Portugal", shortname: "PT"},
  {name: "Puerto Rico", shortname: "PR"},
  {name: "Qatar", shortname: "QA"},
  {name: "Reunion", shortname: "RE"},
  {name: "Romania", shortname: "RO"},
  {name: "Russian Federation", shortname: "RU"},
  {name: "Rwanda", shortname: "RW"},
  {name: "Saint Kitts and Nevis", shortname: "KN"},
  {name: "Saint Lucia", shortname: "LC"},
  {name: "Saint Vincent and the Grenadines", shortname: "VC"},
  {name: "Samoa", shortname: "WS"},
  {name: "San Marino", shortname: "SM"},
  {name: "Sao Tome and Principe", shortname: "ST"},
  {name: "Saudi Arabia", shortname: "SA"},
  {name: "Senegal", shortname: "SN"},
  {name: "Serbia", shortname: "RS"},
  {name: "Seychelles", shortname: "SC"},
  {name: "Sierra Leone", shortname: "SL"},
  {name: "Singapore", shortname: "SG"},
  {name: "Slovakia", shortname: "SK"},
  {name: "Slovenia", shortname: "SI"},
  {name: "Solomon Islands", shortname: "SB"},
  {name: "Somalia", shortname: "SO"},
  {name: "South Africa", shortname: "ZA"},
  {name: "South Georgia South Sandwich Islands", shortname: "GS"},
  {name: "South Sudan", shortname: "SS"},
  {name: "Spain", shortname: "ES"},
  {name: "Sri Lanka", shortname: "LK"},
  {name: "St. Helena", shortname: "SH"},
  {name: "St. Pierre and Miquelon", shortname: "PM"},
  {name: "Sudan", shortname: "SD"},
  {name: "Suriname", shortname: "SR"},
  {name: "Svalbard and Jan Mayen Islands", shortname: "SJ"},
  {name: "Swaziland", shortname: "SZ"},
  {name: "Sweden", shortname: "SE"},
  {name: "Switzerland", shortname: "CH"},
  {name: "Syrian Arab Republic", shortname: "SY"},
  {name: "Taiwan", shortname: "TW"},
  {name: "Tajikistan", shortname: "TJ"},
  {name: "Tanzania, United Republic of", shortname: "TZ"},
  {name: "Thailand", shortname: "TH"},
  {name: "Togo", shortname: "TG"},
  {name: "Tokelau", shortname: "TK"},
  {name: "Tonga", shortname: "TO"},
  {name: "Trinidad and Tobago", shortname: "TT"},
  {name: "Tunisia", shortname: "TN"},
  {name: "Turkey", shortname: "TR"},
  {name: "Turkmenistan", shortname: "TM"},
  {name: "Turks and Caicos Islands", shortname: "TC"},
  {name: "Tuvalu", shortname: "TV"},
  {name: "Uganda", shortname: "UG"},
  {name: "Ukraine", shortname: "UA"},
  {name: "United Arab Emirates", shortname: "AE"},
  {name: "United Kingdom", shortname: "GB"},
  {name: "United States", shortname: "US"},
  {name: "United States minor outlying islands", shortname: "UM"},
  {name: "Uruguay", shortname: "UY"},
  {name: "Uzbekistan", shortname: "UZ"},
  {name: "Vanuatu", shortname: "VU"},
  {name: "Vatican City State", shortname: "VA"},
  {name: "Venezuela", shortname: "VE"},
  {name: "Vietnam", shortname: "VN"},
  {name: "Virgin Islands (British)", shortname: "VG"},
  {name: "Virgin Islands (U.S.)", shortname: "VI"},
  {name: "Wallis and Futuna Islands", shortname: "WF"},
  {name: "Western Sahara", shortname: "EH"},
  {name: "Yemen", shortname: "YE"},
  {name: "Zaire", shortname: "ZR"},
  {name: "Zambia", shortname: "ZM"},
  {name: "Zimbabwe", shortname: "ZW"}
])
Driver.create!([
  {name: "Sebastian Vettel", description: nil, country_id: 80, number: nil},
  {name: "Kimi Raikkonen", description: nil, country_id: 71, number: nil},
  {name: "Sergio Pérez", description: nil, country_id: 142, number: nil},
  {name: "Esteban Ocon", description: nil, country_id: 72, number: nil},
  {name: "Romain Grosjean", description: nil, country_id: 72, number: nil},
  {name: "Kevin Magnussen ", description: nil, country_id: 56, number: nil},
  {name: "Stoffel Vandoorne", description: nil, country_id: 21, number: nil},
  {name: "Fernando Alonso", description: nil, country_id: 203, number: nil},
  {name: "Lewis Hamilton", description: nil, country_id: 230, number: nil},
  {name: "Valteri Bottas", description: nil, country_id: 71, number: nil},
  {name: "Daniel Ricciardo", description: nil, country_id: 13, number: nil},
  {name: "Max Verstappen", description: nil, country_id: 155, number: nil},
  {name: "Nico Hulkenberg", description: nil, country_id: 80, number: nil},
  {name: "Carlos Sainz Jr.", description: nil, country_id: 203, number: nil},
  {name: "Marcus Ericsson", description: nil, country_id: 211, number: nil},
  {name: "Charles Leclerc", description: nil, country_id: 145, number: nil},
  {name: "Pierre Gasly", description: nil, country_id: 72, number: nil},
  {name: "Brendon Hartley", description: nil, country_id: 13, number: nil},
  {name: "Lance Stroll", description: nil, country_id: 38, number: nil},
  {name: "Sergey Sirotkin", description: nil, country_id: 182, number: nil}
])
PowerUnit.create!([
  {name: "Ferrari 062 EVO", description: nil},
  {name: "Mercedes M09 EQ Power+ ", description: nil},
  {name: "Renault R.E.18", description: nil},
  {name: "TAG Heuer", description: nil},
  {name: "Honda RA618H", description: nil}
])
Team.create!([
  {name: "Ferrari", description: nil},
  {name: "Force India", description: nil},
  {name: "Haas", description: nil},
  {name: "McLaren", description: nil},
  {name: "Mercedes", description: nil},
  {name: "Red Bull Racing", description: nil},
  {name: "Renault", description: nil},
  {name: "Sauber", description: nil},
  {name: "Scuderia Toro Rosso", description: nil},
  {name: "Williams", description: nil}
])
Participant.create!([
  {entrant: "Scuderia Ferrari", color: '#C30000', constructor: "Ferrari", chassis: "SF71H", country_id: 106, championship_id: 1, team_id: 1, power_unit_id: 1},
  {entrant: "Sahara Force India F1 Team", color: '#FF80C7', constructor: "Force India-Mercedes", chassis: "VJM11", country_id: 99, championship_id: 1, team_id: 2, power_unit_id: 2},
  {entrant: "Racing Point Force India F1 Team", color: '#FF80C7', constructor: "Force India-Mercedes", chassis: "VJM111", country_id: 230, championship_id: 1, team_id: 2, power_unit_id: 2},
  {entrant: "Haas F1 Team", color: '#6C0000', constructor: "Haas-Ferrari", chassis: "VF-18", country_id: 231, championship_id: 1, team_id: 3, power_unit_id: 1},
  {entrant: "McLaren F1 Team", color: '#FF7B08', constructor: "McLaren-Renault", chassis: "MCL33", country_id: 230, championship_id: 1, team_id: 4, power_unit_id: 3},
  {entrant: "Mercedes AMG Petronas Motorsport", color: '#00CFBA', constructor: "Mercedes", chassis: "F1 W09 EQ Power+", country_id: 80, championship_id: 1, team_id: 5, power_unit_id: 2},
  {entrant: "Aston Martin Red Bull Racing", color: '#00007D', constructor: "Red Bull Racing-TAG Heuer", chassis: "RB14", country_id: 14, championship_id: 1, team_id: 6, power_unit_id: 4},
  {entrant: "Renault Sport Formula One Team", color: '#FFD8C7', constructor: "Renault", chassis: "R. S. 18", country_id: 72, championship_id: 1, team_id: 7, power_unit_id: 3},
  {entrant: "Alfa Romeo Sauber F1 Team", color: '#006EFF', constructor: "Sauber-Ferrari", chassis: "C37", country_id: 212, championship_id: 1, team_id: 8, power_unit_id: 1},
  {entrant: "Red Bull Toro Rosso Honda", color: '#0000FF', constructor: "Scuderia Toro Ross-Honda", chassis: "SSTR13", country_id: 106, championship_id: 1, team_id: 9, power_unit_id: 5},
  {entrant: "Williams Martini Racing ", color: '#FFFFFF', constructor: "Williams-Mercedes", chassis: "FW41", country_id: 230, championship_id: 1, team_id: 10, power_unit_id: 2}
])
Selection.create!([
  {participant_id: 1, driver_id: 1, number: 5},
  {participant_id: 1, driver_id: 2, number: 7},
  {participant_id: 2, driver_id: 3, number: 11},
  {participant_id: 2, driver_id: 4, number: 31},
  {participant_id: 3, driver_id: 3, number: 11},
  {participant_id: 3, driver_id: 4, number: 31},
  {participant_id: 4, driver_id: 5, number: 8},
  {participant_id: 4, driver_id: 6, number: 20},
  {participant_id: 5, driver_id: 7, number: 2},
  {participant_id: 5, driver_id: 8, number: 14},
  {participant_id: 6, driver_id: 9, number: 44},
  {participant_id: 6, driver_id: 10, number: 77},
  {participant_id: 7, driver_id: 11, number: 3},
  {participant_id: 7, driver_id: 12, number: 33},
  {participant_id: 8, driver_id: 13, number: 27},
  {participant_id: 8, driver_id: 14, number: 55},
  {participant_id: 9, driver_id: 15, number: 9},
  {participant_id: 9, driver_id: 16, number: 16},
  {participant_id: 10, driver_id: 17, number: 10},
  {participant_id: 10, driver_id: 18, number: 28},
  {participant_id: 11, driver_id: 19, number: 18},
  {participant_id: 11, driver_id: 20, number: 35}
])
